replicaCount: 1

image:
  repository: ghcr.io/bcgov/cas-shipit
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  name: cas-provision-deployer

route:
  clusterHost: apps.silver.devops.gov.bc.ca

gitHub: # https://github.com/Shopify/shipit-engine/blob/master/docs/setup.md#updating-the-configsecretsyml
  appId: "123"
  installationId: "456"
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    private key here
    -----END RSA PRIVATE KEY-----
  oauth:
    id: 123qwe
    secret: 42abc
    team: bcgov/some-team

shipit:
  web:
    puma_workers: 4

database:
  releaseName: cas-shipit-db
  chartName: cas-postgres-cluster
  user: shipit

# TODO: Remove this once PGO is deployed
cas-postgres:
  patroni:
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 20m
        memory: 400Mi
    persistentVolume:
      storageClass: netapp-block-standard
      size: 4Gi
    replicaCount: 3
    env:
      ALLOW_NOSSL: true

redis:
  global:
    imagePullSecrets:
      - dockerhub-registry
  storageClass: netapp-block-standard
  master:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 64Mi
  replica:
    replicaCount: 1
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 64Mi
  auth:
    # We are providing our own secret as the redis chart regenerates the password with every deploy
    existingSecret: cas-shipit-redis
    existingSecretPasswordKey: redis-password

patroni-migration:
  migrationJob:
    image: postgres
    tag: 17

  deployment:
    sourceReleaseName: cas-shipit
    name: cas-shipit-web
    targetReleaseName: cas-shipit-db
    originalReplicaCount: 3

  from:
    # Assuming all database information will be in the same secret
    # Pass either the secret's key or the specific value
    secretName: cas-shipit-patroni
    hostSecretKey: ~
    host: cas-shipit-patroni.0fad32-tools.svc.cluster.local
    passwordSecretKey: password-superuser
    password: ~
    portSecretKey: ~
    port: 5432
    userSecretKey: ~
    user: postgres

    # The name of the database to migrate
    db: postgres

  to:
    # This is necessarily a PGO deployment
    # superuser to migrate roles
    superuserSecretName: cas-shipit-db-cas-postgres-cluster-pguser-postgres
    # new owner of database to run own the migrated database
    appuserSecretName: cas-shipit-db-cas-postgres-cluster-pguser-shipit
