replicaCount: 1

image:
  repository: ghcr.io/bcgov/cas-shipit
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  name: cas-provision-deployer

route:
  clusterHost: apps.silver.devops.gov.bc.ca

gitHub: # https://github.com/Shopify/shipit-engine/blob/master/docs/setup.md#updating-the-configsecretsyml
  appId: "123"
  installationId: "456"
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    private key here
    -----END RSA PRIVATE KEY-----
  oauth:
    id: 123qwe
    secret: 42abc
    team: bcgov/some-team

shipit:
  web:
    puma_workers: 4

database:
  releaseName: cas-shipit-db
  chartName: cas-postgres-cluster
  user: shipit

redis:
  global:
    imagePullSecrets:
      - dockerhub-registry
  storageClass: netapp-block-standard
  master:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 64Mi
  replica:
    replicaCount: 1
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 30m
        memory: 64Mi
  auth:
    # We are providing our own secret as the redis chart regenerates the password with every deploy
    existingSecret: cas-shipit-redis
    existingSecretPasswordKey: redis-password
