
replicaCount: 1

image:
  repository: gcr.io/ggl-cas-storage/cas-shipit
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  name: cas-provision-deployer

route:
  clusterHost: apps.silver.devops.gov.bc.ca

gitHub: # https://github.com/Shopify/shipit-engine/blob/master/docs/setup.md#updating-the-configsecretsyml
  appId:
  installationId: 
  privateKey: 
  oauth:
    id:
    secret:
    team:

cas-postgres:
  patroni:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 15m
        memory: 600Mi
    persistentVolume:
      storageClass: netapp-block-standard
      size: 4Gi
    replicaCount: 3
    env:
      ALLOW_NOSSL: true

redis:
  global:
    imagePullSecrets:
      - dockerhub-registry
  storageClass: netapp-block-standard
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false