apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${PREFIX}shipit
    spec:
      ports:
        - name: ${PREFIX}shipit
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        name: ${PREFIX}shipit-web
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
