apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cas-shipit.fullname" . }}-redis
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "cas-shipit.labels" . | indent 4 }}
type: Opaque
data:
  redis-password: {{ randAlphaNum 32 | b64enc | quote }}

