apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cas-shipit.fullname" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "cas-shipit.labels" . | indent 4 }}
type: Opaque
data:
  secret_key_base: {{ randAlphaNum 32 | b64enc | quote }}
  github_app_id: {{ .Values.gitHub.appId | b64enc | quote }}
  github_installation_id: {{ .Values.gitHub.installationId | b64enc | quote }}
  github_private_key: {{ .Values.gitHub.privateKey | b64enc | quote }}
  github_oauth_id: {{ .Values.gitHub.oauth.id | b64enc | quote }}
  github_oauth_secret: {{ .Values.gitHub.oauth.secret |  b64enc | quote }}
  github_oauth_team: {{ .Values.gitHub.oauth.team |  b64enc | quote }}

