apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cas-shipit.fullname" . }}-minutely
  labels: {{ include "cas-shipit.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels: {{ include "cas-shipit.labels" . | nindent 12 }}
        spec:
          containers:
            - args:
                - bash
                - -c
                - bundle exec rake cron:minutely
              command:
                - /usr/bin/env
              env: {{ include "cas-shipit.envVariables" . | nindent 16 }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              name: {{ include "cas-shipit.fullname" . }}-cron
              resources:
                limits:
                  cpu: 500m
                  memory: 1Gi
                requests:
                  cpu: 250m
                  memory: 512Mi
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 300
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  suspend: true
