version: 2.1

jobs:

  bundle:
    docker:
      - image: circleci/ruby:2.5.3-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Bundler Package Cache
          keys:
            - cas-shipit-bundle-v2-{{ checksum "Gemfile.lock" }}
            - cas-shipit-bundle-v2-
      - run:
          name: Bundle install dependencies
          command: bundle check || bundle install
      - save_cache:
          name: Save Bundler Package Cache
          key: cas-shipit-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/
          paths:
            - .

  test:
    docker:
      - image: circleci/ruby:2.5.3-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
          PGHOST: 127.0.0.1
          PGUSER: cas-shipit
      - image: circleci/postgres:11.4
        environment:
          POSTGRES_USER: cas-shipit
          POSTGRES_DB: cas_shipit_test
          POSTGRES_PASSWORD: ''
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup the database
          command: ./bin/rake db:setup
      - run:
          name: Run the tests
          command: ./bin/rake test

  verify:
    docker:
      - image: circleci/ruby:2.5.3-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install the latest shipit-engine migrations
          command: ./bin/rake shipit:install:migrations
      - run:
          name: Verify no upstream migrations have been missed
          command: git diff --quiet

  audit:
    docker:
      - image: circleci/ruby:2.5.3-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Audit the bundle
          command: bundle audit check --update --ignore CVE-2015-9284

workflows:
  version: 2
  test:
    jobs:
      - bundle
      - test:
          requires:
            - bundle
      - verify:
          requires:
            - bundle
