version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0

jobs:
  bundle:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
    steps:
      - checkout
      - restore_cache:
          name: Restore Bundler Package Cache
          keys:
            - cas-shipit-bundle-v2-{{ checksum "Gemfile.lock" }}
            - cas-shipit-bundle-v2-
      - run:
          name: Install required version of bundler
          command: gem install bundler:2.5.7
      - run:
          name: Bundle install dependencies
          command: bundle check || bundle install
      - save_cache:
          name: Save Bundler Package Cache
          key: cas-shipit-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/
          paths:
            - .

  test:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
          PGHOST: 127.0.0.1
          PGUSER: cas-shipit
      - image: cimg/postgres:14.11
        environment:
          POSTGRES_USER: cas-shipit
          POSTGRES_DB: cas_shipit_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: cimg/redis:7.2
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install required version of bundler
          command: gem install bundler:2.5.7
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup the database
          command: ./bin/rake db:setup
      - run:
          name: Run the tests
          command: ./bin/rake test

  verify:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install required version of bundler
          command: gem install bundler:2.5.7
      - run:
          name: Install the latest shipit-engine migrations
          command: ./bin/rake shipit:install:migrations
      - run:
          name: Verify no upstream migrations have been missed
          command: git diff --quiet

  audit:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_FROZEN: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install required version of bundler
          command: gem install bundler:2.5.7
      - run:
          name: Audit the bundle
          command: gem install bundler-audit && bundle-audit check

  oc_lint:
    executor: redhat-openshift/default
    steps:
      - checkout
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 4.x
          server-address: $OC_SILVER_SERVER_ADDRESS
          token: $OC_SILVER_TOKEN
      - run:
          name: install helm
          command: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          command: ENVIRONMENT=$OC_SILVER_LINTER_NAMESPACE make lint
          name: Lint the openshift yaml

workflows:
  version: 2
  test:
    jobs:
      - bundle
      - test:
          requires:
            - bundle
      - verify:
          requires:
            - bundle
      - audit:
          requires:
            - bundle
      - oc_lint:
          context: cas-pipeline
          requires:
            - test
            - verify
