apiVersion: template.openshift.io/v1
kind: Template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${PREFIX}shipit-worker-data
  spec:
    storageClassName: netapp-file-standard
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
