development:
  secret_key_base: fc75904f15545dabdca16fa1e73aac1799f69fe56967b1f3b4a0261ac512b5bdd1e64a984c99c0f3533bb26be07dbfe2684934c0c24efa43ccb93833cff58c50
  host: 'http://localhost:3000'
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id:
      secret:
      # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team

test:
  secret_key_base: 8337dd556facaa8d7dd3f1b9c2438d77169e751122b8bde0a67ad49d077ff457422031bb2a9e274092a5c150196351cb6401aac3e45839b72f2d04435c906b34
  host: 'http://localhost:4000'
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['SHIPIT_HOST'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  github:
    domain: # defaults to github.com
    app_id: <%= ENV['GITHUB_APP_ID'] %>
    installation_id: <%= ENV['GITHUB_APP_ID'] %>
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team
  env:
    # SSH_AUTH_SOCK: /foo/bar # You can set environment variable that will be present during deploys.
