development:
  app_name: CAS Shipit
  secret_key_base: 2ddf15eeb45cc7cf5de3f68ddf08bef867b299f95dd3cc15e179af39af19a50b1000735a037923aaba322c64744d76bdb3e147aa90f02488bf30ce59988e45d7
  host: "http://localhost:3000"
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id:
      secret:
      # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team

test:
  app_name: CAS Shipit
  secret_key_base: a02e75d0c3a3ed7382042327058536b712cb3803239067de5776c6a9c383d14776fce210c0c641eb39df72bd3660d26887193f6e66bb785dfe13b203d25525af
  host: "http://localhost:4000"
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team

production:
  app_name: CAS Shipit
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['SHIPIT_HOST'] %>
  redis_url: redis://:<%= ENV['REDIS_PASSWORD'] %>@<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] || 6379 %>
  github:
    # domain: # defaults to github.com
    app_id: <%= ENV['GITHUB_APP_ID'] %>
    installation_id: <%= ENV['GITHUB_INSTALLATION_ID'] %>
    # webhook_secret:
    private_key: <%= ENV['GITHUB_PRIVATE_KEY'] %>
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      teams:
        - <%= ENV['GITHUB_OAUTH_TEAM'] %>
  # env:
    # SSH_AUTH_SOCK: /foo/bar # You can set environment variable that will be present during deploys.
