development:
  app_name: CAS Shipit
  secret_key_base: d3bebbd1760891d30b081da1d87f92bbaae2d56621947616b4f2bc082e572ec7c7398425f98b2a57023555fe2f702fef8168ee9887c48234163c5c0e3dbc8dc4
  host: "http://localhost:3000"
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id:
      secret:
      # team: MyOrg/developers # Enable this setting to restrict access to only the member of a team

test:
  app_name: CAS Shipit
  secret_key_base: 57124b973e28ed12d36bdc77bd359596908b14ef575491140e829efdbdccda5c9c1907a65887557a6ee39a17f1ab0d9f5468f1e77ca553f5c2567b1fa7c0b3de
  host: "http://localhost:4000"
  redis_url: redis://localhost
  github:
    domain: # defaults to github.com
    bot_login:
    app_id:
    installation_id:
    webhook_secret:
    private_key:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      # teams: MyOrg/developers # Enable this setting to restrict access to only the member of a team

production:
  app_name: CAS Shipit
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  host: <%= ENV['SHIPIT_HOST'] %>
  redis_url: redis://:<%= ENV['REDIS_PASSWORD'] %>@<%= ENV['REDIS_HOST'] %>:<%= ENV['REDIS_PORT'] || 6379 %>
  github:
    # domain: github.com # defaults to github.com
    app_id: <%= ENV['GITHUB_APP_ID'] %>
    installation_id: <%= ENV['GITHUB_INSTALLATION_ID'] %>
    # webhook_secret:
    oauth:
      id: <%= ENV['GITHUB_OAUTH_ID'] %>
      secret: <%= ENV['GITHUB_OAUTH_SECRET'] %>
      teams:
        - <%= ENV['GITHUB_OAUTH_TEAM'] %>
    private_key: |-
<%= ENV.fetch('GITHUB_PRIVATE_KEY', "").indent(6) %>
  # env:
    # SSH_AUTH_SOCK: /foo/bar # You can set environment variable that will be present during deploys.
    