apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cas-shipit.fullname" . }}-worker-data
  labels:
{{ include "cas-shipit.labels" . | indent 4 }}
spec:
  storageClassName: netapp-file-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
