apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: Base64-encoded rails master key.
    displayName: Rails master key
    name: RAILS_MASTER_KEY
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        beta.kubernetes.io/os: linux
      name: ${PREFIX}shipit
    type: Opaque
    data:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
