apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: Base64-encoded password.
    displayName: Postgres database password
    name: POSTGRES_PASSWORD_BASE_64
    required: true

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        beta.kubernetes.io/os: linux
      name: ${PREFIX}shipit-postgres
    type: Opaque
    data:
      database-password: ${POSTGRES_PASSWORD_BASE_64}
