apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Openshift project name.
    displayName: Project
    name: OC_PROJECT
    required: true
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true

objects:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${PREFIX}shipit
    spec:
      host: ${PREFIX}shipit.pathfinder.gov.bc.ca
      port:
        targetPort: ${PREFIX}shipit-web
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: ${PREFIX}shipit
        weight: 100
      wildcardPolicy: None
    status:
      ingress:
        - conditions:
            - status: "True"
              type: Admitted
          host: ${PREFIX}shipit.pathfinder.gov.bc.ca
          routerName: router
          wildcardPolicy: None
