apiVersion: template.openshift.io/v1
kind: Template

parameters:
  - description: Prefix to prepend to object name.
    displayName: Prefix
    name: PREFIX
    required: true
  - description: SHA1 of git revision to be deployed.
    displayName: Git SHA1
    name: GIT_SHA1
    required: true
  - description: Openshift project name
    displayName: Project
    name: OC_PROJECT
    required: true
  - description: Openshift registry URL
    displayName: Registry
    name: OC_REGISTRY
    required: true
  - description: Postgres Database Password
    displayName: Postgres Database Password
    name: POSTGRES_PASSWORD

objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: ${PREFIX}shipit-minutely
    spec:
      concurrencyPolicy: Forbid
      failedJobsHistoryLimit: 1
      jobTemplate:
        spec:
          activeDeadlineSeconds: 120
          backoffLimit: 0
          template:
            spec:
              containers:
                - args:
                    - bash
                    - -c
                    - bundle exec rake cron:minutely
                  command:
                    - /usr/bin/env
                  env:
                    - name: RAILS_ENV
                      value: production
                    - name: DATABASE_URL
                      value: postgres://shipit:${POSTGRES_PASSWORD}@cas-shipit-postgres-master:5432/shipit
                    - name: RAILS_MASTER_KEY
                      valueFrom:
                        secretKeyRef:
                          key: RAILS_MASTER_KEY
                          name: ${PREFIX}shipit
                    - name: RAILS_SERVE_STATIC_FILES
                      value: "true"
                  image: ${OC_REGISTRY}/${OC_PROJECT}/${PREFIX}shipit:${GIT_SHA1}
                  imagePullPolicy: Always
                  name: ${PREFIX}shipit-cron
                  resources:
                    limits:
                      cpu: "1"
                      memory: 256Mi
                    requests:
                      cpu: 500m
                      memory: 128Mi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
              dnsPolicy: ClusterFirst
              restartPolicy: Never
              schedulerName: default-scheduler
              securityContext: {}
              terminationGracePeriodSeconds: 30
      schedule: "*/5 * * * *"
      successfulJobsHistoryLimit: 1
      suspend: false
